const $=s=>document.querySelector(s);
const problems=window.problems||[];
const header=(active)=>`<header class="site-header"><div class="nav-shell"><a class="brand" href="index.html"><span class="brand-mark">AC</span><span><b>AJMERA</b><strong>CROSSTOWN</strong></span></a><nav class="desktop-nav"><a class="${active==="home"?"active":""}" href="index.html">Home</a><a class="${active==="society"?"active":""}" href="society.html">Society</a><a class="${active==="facilities"?"active":""}" href="facilities.html">Facilities</a><a class="${active==="parking"?"active":""}" href="parking.html">Parking</a><a class="${active==="maintenance"?"active":""}" href="maintenance.html">Maintenance</a><a class="${active==="infrastructure"?"active":""}" href="infrastructure.html">Infrastructure</a><div class="nav-dropdown"><button>Culture <span>⌄</span></button><div><a href="events.html">Events</a><a href="gallery.html">Gallery</a></div></div><a class="${active==="problems"?"active":""}" href="problems.html">Problems</a><a class="${active==="documents"?"active":""}" href="documents.html">Documents</a><a class="${active==="contacts"?"active":""}" href="contacts.html">Contact</a></nav><button class="menu-btn" id="menuBtn">☰</button></div><div class="mobile-menu" id="mobileMenu"><a href="index.html">Home</a><a href="society.html">Society</a><a href="facilities.html">Facilities</a><a href="parking.html">Parking</a><a href="maintenance.html">Maintenance</a><a href="infrastructure.html">Infrastructure</a><details><summary>Culture</summary><a href="events.html">Events</a><a href="gallery.html">Gallery</a></details><a href="problems.html">Problems & Issues</a><a href="documents.html">Documents</a><a href="contacts.html">Contact</a></div></header>`;
const footer=`<footer><div><a class="brand footer-brand" href="index.html"><span class="brand-mark">AC</span><span><b>AJMERA</b><strong>CROSSTOWN</strong></span></a><p>Resident information portal for the Ajmera Crosstown community.</p></div><div><b>Explore</b><a href="society.html">Society</a><a href="facilities.html">Facilities</a><a href="parking.html">Parking</a><a href="problems.html">Problems</a></div><div><b>Community</b><a href="events.html">Events</a><a href="gallery.html">Gallery</a><a href="documents.html">Documents</a><a href="contacts.html">Contacts</a></div></footer>`;
const page=document.body.dataset.page||location.pathname.split("/").pop().replace(".html","")||"home";
if($("#siteHeader")) $("#siteHeader").outerHTML=header(page);
if($("#siteFooter")) $("#siteFooter").outerHTML=footer;
$("#menuBtn")?.addEventListener("click",()=>$("#mobileMenu")?.classList.toggle("open"));
document.querySelectorAll("#mobileMenu a").forEach(a=>a.addEventListener("click",()=>$("#mobileMenu")?.classList.remove("open")));
const badge=v=>`<span class="badge ${String(v).toLowerCase().replaceAll(" ","-")}">${v}</span>`;
if($("#homeUpdates")) $("#homeUpdates").innerHTML=problems.slice(0,4).map(p=>`<a class="update-card" href="problems.html"><div><b>${p.title}</b><small>${p.category} · ${p.updated}</small></div>${badge(p.status)}</a>`).join("");
if($("#breakupList")) $("#breakupList").innerHTML=[["Regular Maintenance","₹2,500"],["Security","₹800"],["Water Charges","₹700"],["Lift Maintenance","₹600"],["Common Area Cleaning","₹500"],["Repairs & AMC","₹700"],["Sinking Fund","₹400"],["Other Charges","₹300"]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")+`<div class="breakup-total"><span>Total</span><b>₹6,500</b></div>`;
const search=$("#problemSearch"),status=$("#statusFilter"),category=$("#categoryFilter"),wing=$("#wingFilter");
function renderProblems(){if(!$("#problemRows"))return;const q=(search?.value||"").toLowerCase(),st=status?.value||"All status",cat=category?.value||"All categories",w=wing?.value||"All wings";const rows=problems.filter(p=>(!q||[p.id,p.title,p.category,p.location,p.priority,p.status,...p.pocs].join(" ").toLowerCase().includes(q))&&(st==="All status"||p.status===st)&&(cat==="All categories"||p.category===cat)&&(w==="All wings"||p.location.toLowerCase().includes(w.toLowerCase())));$("#problemRows").innerHTML=rows.map(p=>`<button type="button" class="problem-row" data-id="${p.id}"><span>${p.id}</span><strong>${p.title}</strong><span>${p.category}</span><span>${p.location}</span><span>${badge(p.priority)}</span><span>${badge(p.status)}</span><span>${p.pocs.length}</span><span>${p.updated}</span></button>`).join("")||"<div class='card'>No matching problems found.</div>";document.querySelectorAll(".problem-row").forEach(r=>r.onclick=()=>openProblem(r.dataset.id))}
function openProblem(id){const p=problems.find(x=>x.id===id);if(!p)return;$("#modalContent").innerHTML=`<div class="eyebrow">${p.id} · ${p.category}</div><div class="modal-title"><h2>${p.title}</h2>${badge(p.status)}</div><p class="modal-description">${p.description}</p><div class="detail-grid"><div><small>Location</small><b>${p.location}</b></div><div><small>Priority</small><b>${p.priority}</b></div><div><small>Reported</small><b>${p.reported}</b></div><div><small>Updated</small><b>${p.updated}</b></div></div><div class="poc-box"><b>POC(s)</b><div>${p.pocs.map(x=>`<span>${x}</span>`).join("")}</div></div><div class="timeline">${p.timeline.map(t=>`<div><i></i><small>${t[0]}</small><b>${t[1]}</b><p>${t[2]}</p></div>`).join("")}</div><div class="resolution"><b>Resolution</b><p>${p.resolution}</p></div>`;$("#problemModal").classList.add("open")}
function closeModal(){$("#problemModal")?.classList.remove("open")}
[search,status,category,wing].filter(Boolean).forEach(e=>e.addEventListener(e.tagName==="INPUT"?"input":"change",renderProblems));
$("#modalClose")?.addEventListener("click",closeModal);$("#problemModal")?.addEventListener("click",e=>{if(e.target.id==="problemModal")closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
let level="P0";if($("#parkingTabs")){$("#parkingTabs").innerHTML=["P0","P1","P2","P3","P4"].map((x,i)=>`<button class="${i?"":"active"}" data-level="${x}">${x}</button>`).join("");document.querySelectorAll("#parkingTabs button").forEach(b=>b.onclick=()=>{level=b.dataset.level;document.querySelectorAll("#parkingTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderParking()})}
function renderParking(){if(!$("#slotGrid"))return;const available=level==="P0"?new Set([23,47]):new Set();$("#slotGrid").innerHTML=Array.from({length:50},(_,i)=>{const n=i+1,a=available.has(n);return`<button class="slot ${a?"available":""}" data-n="${n}">${String(n).padStart(2,"0")}</button>`}).join("");document.querySelectorAll(".slot").forEach(s=>s.onclick=()=>{$("#slotDetails").innerHTML=`<h3>${level} · Slot ${String(s.dataset.n).padStart(2,"0")}</h3><p>${s.classList.contains("available")?"Available":"Purchased"} · ${s.classList.contains("available")?"No flat assigned":"Assigned flat: Sample data"}</p>`})}
renderProblems();renderParking();
if($("#docList")) $("#docList").innerHTML=[["Society Rules & Regulations","Society Rules","12 Jan 2026"],["Latest AGM Minutes","AGM Minutes","05 Jan 2026"],["Fire Safety Certificate","Certificates","20 Dec 2025"],["Water Quality Report","Water Reports","10 Dec 2025"],["Meeting Minutes","Meeting Minutes","08 Dec 2025"]].map(d=>`<div class="doc-row"><span>▤</span><div><b>${d[0]}</b><small>${d[1]} · ${d[2]}</small></div><button type="button">↓</button></div>`).join("");